version: '3.8'

services:
  # ============================================================
  # ShutterSync Quick Analyzer (Flickr)
  # アクセス: http://localhost:3003/flickr/
  # ============================================================
  flickr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flickr
    ports:
      - "3003:80"
    restart: always
    networks:
      - web-network

networks:
  web-network:
    external: true
    name: my-web-server-network
